name: Workflow03
on: 
  push:
    branches:
    - 'main'
  workflow_dispatch:  
jobs:
  job01:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      message: 'Hello! This is production environment...'
    steps:
    - name: Display Message
      run: |
        echo ${{ env.message }}
  job02:
    runs-on: ubuntu-latest
    env:
      message_dev: 'Hello! This is development environment...'
    steps:
    - name: Display Message
      run: |
        echo ${{ env.message_dev }}