name: Workflow02
on: 
  push:
    branches:
    - 'main'
  workflow_dispatch:  
jobs:
  job01:
    runs-on: ubuntu-latest
    env:
      message: 'Hello Everyone!'
    steps:
    - name: Display Message
      run: |
        echo ${{ env.message }}